# Generated by Django 5.1.3 on 2024-11-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_rename_voter_vote_user_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(null=True),
        ),
    ]
