# Generated by Django 5.1.1 on 2024-11-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='user',
        ),
        migrations.AddField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alumni_images/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
