# Generated by Django 5.1.3 on 2024-11-28 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('General Secretary', 'General Secretary'), ('Treasurer', 'Treasurer'), ('PR Officer', 'Public Relations Officer'), ('Technical Coordinator', 'Technical Coordinator'), ('Event Coordinator', 'Event Coordinator'), ('Creative Head', 'Creative Head'), ('Membership Coordinator', 'Membership Coordinator'), ('Training Head', 'Training and Development Head'), ('Web Admin', 'Web Administrator'), ('Social Media Manager', 'Social Media Manager'), ('Logistics Head', 'Logistics Head'), ('Outreach Coordinator', 'Outreach Coordinator'), ('Research Lead', 'Research and Innovation Lead'), ('Alumni Coordinator', 'Alumni Coordinator')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('linkedIn', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
