# Generated by Django 5.1.1 on 2024-11-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
